In [1]:
#LAB 9

In [ ]:
1. Create a 2D numpy array from the user input and arrange the elements.
2. Create a numpy array of mXn with the random values between k to l. [m,n,k,l all the values will
be given by user.

In [3]:
#QUESTION 1
import numpy as np

list_1 = []
n = int(input("Enter the no of lists:"))
for i in range(n):
    list_i = []
    a = int(input("Enter no of elements:"))
    for k in range(a):
        b = int(input("Enter the element"))
        list_i.append(b)
    list_1.append(list_i)
print("List of Lists:", list_1)
print(np.array(list_1))

Enter the no of lists: 4
Enter no of elements: 4
Enter the element 1
Enter the element 2
Enter the element 3
Enter the element 4
Enter no of elements: 4
Enter the element 1
Enter the element 2
Enter the element 3
Enter the element 4
Enter no of elements: 4
Enter the element 1
Enter the element 2
Enter the element 3
Enter the element 4
Enter no of elements: 4
Enter the element 1
Enter the element 2
Enter the element 3
Enter the element 4


List of Lists: [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [4]:
#QUESTION 2

import numpy as np

m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))
k = int(input("Enter the upper bound for random values (k): "))

user_array = np.random.randint(1, k+1, size=(m, n))

print("Random m x n NumPy Array with values between 1 and k:")
print(user_array)

Enter the number of rows (m):  3
Enter the number of columns (n):  4
Enter the upper bound for random values (k):  1


Random m x n NumPy Array with values between 1 and k:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
